### ISSUE TITLE
Moving windows for daylie/weekly task lists for alts has x/y position issues

### ISSUE THREAD

**Issue by tmtProdigy** [dailyark/dailyark.github.io#22]
Browser: Microsoft Edge on Windows

When moving the windowsubon klicking the move icon to drag and drop, the window jumps to seemling random places, when selecting it a second time to move it then works, makes rearranging the windows very difficult

(thanks for the tool, absolutely amazing otherwise!)

**Comment by dailyark** [comment]
Try a Ctrl + F5 see if that solves the issue.
As I've fixed the issue you are describing a few days ago. And I just tested it in 4 different browsers, where it works perfectly.

**Comment by tmtProdigy** [comment]
Still the same issue unfortunately, could it have something to do with the amount of windows? i tried brave browser and manually adding characters it seemed fine first, then i exported/imported (9 characters) and now i have the same issue in brave browser as i had in edge.

**Comment by dailyark** [comment]
Would it be possible for you to make a video of what you are experiencing, while having your console open? (F12)
As I've just done the same as you (bar using brave, because brave is bad mmkay) and cannot replicate it.

**Comment by tmtProdigy** [comment]
Sure thing, coming up!

**Comment by tmtProdigy** [comment]
in the video you can see as soon as i click the move icon to drag and drop, the window pops to a difference space on the canves (if i hold left mouse button i can actually move the windows where it is, i justn dont see it) 

upon reseting positions i have noticed the first time i move the window, it works, but moving it a second time, the issue re-appears, also shown in the video: 

https://streamable.com/z30md7

console doesnt show much from what i can see, just privacy badger/ublock doing its thing presumably.

**Comment by dailyark** [comment]
Yeah, it's strange, as those are the exact issues I had fixed a few days ago. 
And I can't replicate it on any of my browsers currently. 

And judging by the Data navbar, you do have the latest version loaded into your cache 🤔 

Could you send me your export file, maybe it's something in your characters names? (grasping at straws here)

**Comment by tmtProdigy** [comment]
[new export.zip](https://github.com/dailyark/dailyark.github.io/files/8306820/new.export.zip)

sure thing here you go - since i found out that moving it the first time after reset has no issues, i was able to sort it nicely, so not urgent at all, and i guess if only i have the issue, chances are the issue lies in some way with my environment/configuration, so no worries if you don't get around to it!

**Comment by dailyark** [comment]
Ok I can replicate it with your export. Atleast that gives me something to look at. Thanks!

**Comment by tmtProdigy** [comment]
cheers!

**Comment by plycaeus** [comment]
If it helps, I also have the same problem; it's normal for the roster and both characters' windows, however for my third character each time I try to move it it just jumps to wherever.

I use the latest version of Firefox and have refreshed the page to obtain the latest version.
